# Generated by Django 4.1.7 on 2023-02-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('home_number', models.IntegerField(verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Завод',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('type', models.CharField(max_length=30, verbose_name='Модель')),
                ('supplier', models.CharField(max_length=30, verbose_name='Поставщик')),
                ('date_issue', models.DateTimeField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.factory')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.retailnetwork')),
            ],
            options={
                'verbose_name': 'Предприниматель',
            },
        ),
    ]
